In [30]:
import numpy as np
import matplotlib.pyplot as plt

# Cholesky decomposition

In [ ]:
from numpy.linalg import cholesky
from numpy.testing import assert_allclose

In [2]:
nvel = 19
ndof = nvel*2
ncons = 5

slice_zero = np.s_[:ncons, :ncons]
slice_non_zero = np.s_[ncons:, ncons:]

A = np.zeros((ndof, ndof))
L = np.zeros((ndof, ndof))

for i in range(ncons, ndof, 1):
    A[i, i] = 2

L[slice_non_zero] = cholesky(A[slice_non_zero])

In [3]:
A[5, 5]

2.0

## Test case 1

Looking at identical values in the diagonal, not including those in the ncons values

In [4]:
nvel = 19
ndof = nvel*2
ncons = 5

A = np.zeros(ndof*ndof)
L_test = np.zeros(ndof*ndof)

for i in range(0, ndof, 1):
    A[i*ndof + i] = 2
    L_test[i*ndof + i] = np.sqrt(2)

A = A.reshape((ndof, ndof))
L = cholesky(A)

assert_allclose(L.flatten(), L_test)

## Test case 2

Looking at variable values in the diagonal, but ensuring the matrix is still positive definite

In [5]:
nvel = 19
ndof = nvel*2
ncons = 5

A = np.zeros(((ndof - ncons), (ndof - ncons)))
L_test = np.zeros_like(A)
A.shape

for i in range(0, ndof - ncons):
    A[i, i] = i + 1
    L_test[i, i] = np.sqrt(i + 1)

L = cholesky(A)
assert_allclose(L, L_test)

## Test case 3

Looking at assigning positive random variables to the diagonal

In [6]:
nvel = 19
ndof = nvel*2
ncons = 5

A = np.zeros(((ndof - ncons), (ndof - ncons)))
L_test = np.zeros_like(A)
A.shape

for i in range(0, ndof - ncons):
    val = np.random.randint(0, 100)
    A[i, i] = val
    L_test[i, i] = np.sqrt(val)

L = cholesky(A)
assert_allclose(L, L_test)

## Test case 4

Looking at assigning positive random variables to the diagonal along with values at the same locations as those in the Xi matrix

In [7]:
sz = 38
L = np.random.randint(1, sz, size = (sz, sz))
L = L + sz*np.eye(sz)

np.linalg.eigvals(L * L.T)

array([17967.62630236,  7068.1941064 ,  6586.59405152,  -941.14041533,
        -792.32868132,  6185.23389325,  -492.12931482,  6010.39590608,
        5800.11831146,  -132.06321272,   -21.81796392,  5591.22616863,
        5295.05804777,  5239.48291565,  5076.74989672,  4852.38668252,
        4524.34243144,  4570.73963164,  4216.6488032 ,  4013.55150909,
        3842.19603737,  3599.47595708,  3489.9277691 ,  3263.75643814,
         264.66333035,  2822.20596291,  2662.04737272,  2454.79791826,
         621.95784162,  2143.59557391,  2040.92650461,   805.16093548,
        1102.94389966,   979.00377344,  1328.52607106,  1481.09109633,
        1699.47912291,  1695.37532542])

In [26]:
sz = 10
A = np.random.randint(low = 0, high = 5, size = (sz, sz))
A = 0.5 * (A + A.T)
A = A + (sz*np.eye(sz))
A[0:5, 0:5] = 0

L_C = cholesky(A[5:, 5:])

(array([[3.16227766, 0.        , 0.        , 0.        , 0.        ],
        [0.9486833 , 3.17804972, 0.        , 0.        , 0.        ],
        [0.63245553, 0.75518013, 3.60966799, 0.        , 0.        ],
        [0.79056942, 0.23599379, 0.50469522, 3.17247375, 0.        ],
        [0.47434165, 0.33039131, 0.67886993, 1.01006582, 2.8608992 ]]),
 array([[10. ,  0. ,  0. ,  0. ,  0. ],
        [ 3. , 11. ,  0. ,  0. ,  0. ],
        [ 2. ,  3. , 14. ,  0. ,  0. ],
        [ 2.5,  1.5,  2.5, 11. ,  0. ],
        [ 1.5,  1.5,  3. ,  4. , 10. ]]))

In [9]:
nvel = 19
ndof = nvel*2
ncons = 5

A = np.zeros((ndof, ndof))
L_test = np.zeros_like(A)
# A.shape

set_val = 1

for i in range(ncons, ndof):
    A[i, i] = 5
    A[i, ndof - i - 1] = set_val

# np.linalg.eigvals(A)
L = cholesky(A)
L

LinAlgError: Matrix is not positive definite

## Test case 5

Looking at a version of the xi matrix

In [ ]:
nvel = 19
ndof = nvel*2
ncons = 5

A = np.zeros((ndof, ndof))
L_test = np.zeros_like(A)
A.shape

for i in range(ncons, ndof):
    A[i, i] = 39

set_val = 1

A[1, 8] = set_val
A[1, nvel + 1] = set_val
A[2, 5] = set_val
A[3, 6] = set_val
A[4, 7] = set_val
A[8, nvel + 1] = set_val
A[8, 1] = set_val
A[nvel + 1, 1] = set_val
A[5, 2] = set_val
A[6, 3] = set_val
A[7, 4] = set_val
A[nvel + 1, 8] = set_val
A[nvel + 1, 8] = set_val

A[0, nvel + 4] = set_val
A[0, nvel + 16] = set_val
A[1, nvel + 4] = set_val
A[1, nvel + 16] = set_val
A[8, 1] = set_val
A[8, nvel + 4] = set_val
A[8, nvel + 16] = set_val
A[20, nvel + 1] = set_val
A[20, nvel + 4] = set_val
A[20, nvel + 16] = set_val
A[nvel + 4, 0] = set_val
A[nvel + 16, 0] = set_val
A[nvel + 4, 1] = set_val
A[nvel + 16, 1] = set_val
A[1, 8] = set_val
A[nvel + 4, 8] = set_val
A[nvel + 16, 8] = set_val
A[1, 20] = set_val
A[nvel + 4, 20] = set_val
A[nvel + 16, 20] = set_val

A[1, nvel + 4] = set_val
A[1, nvel + 16] = set_val
A[nvel + 1, nvel + 4] = set_val
A[nvel + 1, nvel + 16] = set_val
A[nvel + 4, nvel + 16] = set_val
A[nvel + 4, 1] = set_val
A[nvel + 16, 1] = set_val
A[nvel + 4, nvel + 1] = set_val
A[nvel + 16, nvel + 1] = set_val
A[nvel + 16, nvel + 4] = set_val

np.linalg.eigvals(A)

array([ 4.11837589e+01,  3.80173426e+01,  1.47792862e+00, -6.26615611e-01,
       -5.24144683e-02, -2.56241898e-02,  3.80000000e+01,  3.90256242e+01,
        3.90256242e+01,  3.90256242e+01, -2.56241898e-02, -2.56241898e-02,
        3.90000000e+01,  3.90000000e+01,  3.90000000e+01,  3.90000000e+01,
        3.90000000e+01,  3.90000000e+01,  3.90000000e+01,  3.90000000e+01,
        3.90000000e+01,  3.90000000e+01,  3.90000000e+01,  3.90000000e+01,
        3.90000000e+01,  3.90000000e+01,  3.90000000e+01,  3.90000000e+01,
        3.90000000e+01,  3.90000000e+01,  3.90000000e+01,  3.90000000e+01,
        3.90000000e+01,  3.90000000e+01,  3.90000000e+01,  3.90000000e+01,
        3.90000000e+01,  3.90000000e+01])

# Inverse Fourier Transform

## Test case 1

Sin wave in fft

In [31]:
from numpy.fft import fftn, ifftn

In [37]:
sz = 16
x = np.linspace(0, sz - 1, sz)
X, Y, Z = np.meshgrid(*[x, x, x])

V = np.sin(np.sqrt(X**2 + Y**2 + Z**2))
# plt.imshow(V[8, :, :])
# fig, ax = plt.subplots(subplot_kw={"projection": "3d"})
# ax.plot_surface(X, Y, Z, vmin=Z.min(), cmap= "magma")

In [40]:
V_k = fftn(V)